-- ============================================================
-- BANCO: webapp
-- SCHEMA: public
-- ============================================================



-- ============================================================
-- TB_USUARIO
-- ============================================================
CREATE TABLE tb_usuario (
    cd_usuario BIGSERIAL PRIMARY KEY,
    login VARCHAR(100) NOT NULL,
    senha_hash TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    dt_cadastro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dt_atualizacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dt_ultimo_acesso TIMESTAMPTZ,
    CONSTRAINT uq_tb_usuario_login UNIQUE (login),
    CONSTRAINT ck_tb_usuario_login CHECK (BTRIM(login) <> ''),
    CONSTRAINT ck_tb_usuario_senha CHECK (BTRIM(senha_hash) <> '')
);

--TRUNCATE TABLE tb_contato RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_contato RESTART IDENTITY;

-- ============================================================
-- TB_CONTATO
-- ============================================================
CREATE TABLE drop table tb_contato (
    cd_contato INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nm_contato VARCHAR(80) NOT NULL,
    email VARCHAR(120) NOT NULL,
    celular VARCHAR(20) NOT null,
    comentario VARCHAR(200) NOT null,
    dt_nascimento DATE,
    dt_cadastro TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tb_contato_email UNIQUE (email),
    CONSTRAINT uq_tb_contato_celular UNIQUE (celular)
);


CREATE TABLE tb_logacesso (
    cd_logacesso INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dt_acesso TIMESTAMP NOT NULL,
    ip VARCHAR(45) NOT NULL,
    metodo VARCHAR(10),
    rota VARCHAR(255),
    status_http INTEGER,
    referer VARCHAR(500),
    user_agent VARCHAR(500),
    navegador VARCHAR(50),
    dispositivo VARCHAR(50),
    bot BOOLEAN NOT NULL DEFAULT FALSE,
    cidade VARCHAR(100),
    uf VARCHAR(50),
    pais VARCHAR(50),
    provedor VARCHAR(150),
    dt_cadastro TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================
-- TB_MOEDA
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_moeda
(cd_moeda        integer GENERATED BY DEFAULT AS IDENTITY,
 moeda           varchar(4)      NOT NULL,
 valor           numeric(18, 5)  NOT NULL DEFAULT 0,
 status          boolean         NOT NULL DEFAULT false,
 dt_referencia   timestamp with time zone NOT NULL,
 dt_atualizacao  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT pk_tb_moeda PRIMARY KEY (cd_moeda),
 CONSTRAINT uq_tb_moeda_referencia UNIQUE (moeda, dt_referencia),
 CONSTRAINT ck_tb_moeda_codigo CHECK (char_length(moeda) = 4),
 CONSTRAINT ck_tb_moeda_valor CHECK (valor >= 0)
);


-- ============================================================
-- TB_IPCA
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_ipca
(cd_ipca         integer GENERATED BY DEFAULT AS IDENTITY,
 indice          numeric(8, 5)  NOT NULL DEFAULT 0,
 status          boolean        NOT NULL DEFAULT false,
 dt_referencia   date           NOT NULL,
 dt_atualizacao  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT pk_tb_ipca PRIMARY KEY (cd_ipca),
 CONSTRAINT uq_tb_ipca_referencia UNIQUE (dt_referencia)
);


-- ============================================================
-- TB_SELIC
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_selic
(cd_selic        integer GENERATED BY DEFAULT AS IDENTITY,
 indice          numeric(8, 5)  NOT NULL DEFAULT 0,
 status          boolean        NOT NULL DEFAULT false,
 dt_referencia   date           NOT NULL,
 dt_atualizacao  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_tb_selic PRIMARY KEY (cd_selic),
CONSTRAINT uq_tb_selic_referencia UNIQUE (dt_referencia)
);


-- ============================================================
-- TB_SALARIOMINIMO
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_salariominimo
(cd_salario      integer GENERATED BY DEFAULT AS IDENTITY,
 vl_salario      numeric(10, 2) NOT NULL DEFAULT 0,
 status          boolean        NOT NULL DEFAULT false,
 dt_referencia   date           NOT NULL,
 dt_atualizacao  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_tb_salariominimo PRIMARY KEY (cd_salario),
CONSTRAINT uq_tb_salariominimo_referencia UNIQUE (dt_referencia),
CONSTRAINT ck_tb_salariominimo_valor CHECK (vl_salario >= 0)
);


-- ============================================================
-- TB_CAPITAL
-- Tabela mestre geográfica do WebApp
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_capital
(cd_capital    integer GENERATED BY DEFAULT AS IDENTITY,
 cidade        varchar(50) NOT NULL,
 cidade_busca  varchar(50) NOT NULL,
 uf            char(2)     NOT NULL,
 regiao        varchar(20) NOT NULL,
 cd_ibge       varchar(10) NOT NULL,
 status        boolean     NOT NULL DEFAULT true,
CONSTRAINT pk_tb_capital PRIMARY KEY (cd_capital),
CONSTRAINT uq_tb_capital_cidade_uf UNIQUE (cidade, uf),
CONSTRAINT uq_tb_capital_cidade_busca UNIQUE (cidade_busca),
CONSTRAINT uq_tb_capital_cd_ibge UNIQUE (cd_ibge),
CONSTRAINT ck_tb_capital_regiao CHECK (regiao IN('Brasil', 'Norte', 'Nordeste', 'Centro-Oeste', 'Sudeste', 'Sul'))
);


-- ============================================================
-- REGISTROS ESPECIAIS
-- ============================================================
INSERT INTO public.tb_capital
(cd_capital, cidade, cidade_busca, uf, regiao, cd_ibge)
VALUES (100, 'Brasil', 'BRASIL', 'BR', 'Brasil', '99999'),
       (101, 'Estado', 'ESTADO', 'BR', 'Brasil', '10101')
ON CONFLICT DO NOTHING;


-- ============================================================
-- CAPITAIS
-- ============================================================
INSERT INTO public.tb_capital
(cidade, cidade_busca, uf, regiao, cd_ibge)
VALUES
('Rio Branco',     'RIO BRANCO',      'AC', 'Norte',        '1200401'),
('Maceió',         'MACEIO',          'AL', 'Nordeste',     '2704302'),
('Macapá',         'MACAPA',          'AP', 'Norte',        '1600303'),
('Manaus',         'MANAUS',          'AM', 'Norte',        '1302603'),
('Salvador',       'SALVADOR',        'BA', 'Nordeste',     '2927408'),
('Fortaleza',      'FORTALEZA',       'CE', 'Nordeste',     '2304400'),
('Brasília',       'BRASILIA',        'DF', 'Centro-Oeste', '5300108'),
('Vitória',        'VITORIA',         'ES', 'Sudeste',      '3205309'),
('Goiânia',        'GOIANIA',         'GO', 'Centro-Oeste', '5208707'),
('São Luís',       'SAO LUIS',        'MA', 'Nordeste',     '2111300'),
('Cuiabá',         'CUIABA',          'MT', 'Centro-Oeste', '5103403'),
('Campo Grande',   'CAMPO GRANDE',    'MS', 'Centro-Oeste', '5002704'),
('Belo Horizonte', 'BELO HORIZONTE',  'MG', 'Sudeste',      '3106200'),
('Belém',          'BELEM',           'PA', 'Norte',        '1501402'),
('João Pessoa',    'JOAO PESSOA',     'PB', 'Nordeste',     '2507507'),
('Curitiba',       'CURITIBA',        'PR', 'Sul',          '4106902'),
('Recife',         'RECIFE',          'PE', 'Nordeste',     '2611606'),
('Teresina',       'TERESINA',        'PI', 'Nordeste',     '2211001'),
('Rio de Janeiro', 'RIO DE JANEIRO',  'RJ', 'Sudeste',      '3304557'),
('Natal',          'NATAL',           'RN', 'Nordeste',     '2408102'),
('Porto Alegre',   'PORTO ALEGRE',    'RS', 'Sul',          '4314902'),
('Porto Velho',    'PORTO VELHO',     'RO', 'Norte',        '1100205'),
('Boa Vista',      'BOA VISTA',       'RR', 'Norte',        '1400100'),
('Florianópolis',  'FLORIANOPOLIS',   'SC', 'Sul',          '4205407'),
('São Paulo',      'SAO PAULO',       'SP', 'Sudeste',      '3550308'),
('Aracaju',        'ARACAJU',         'SE', 'Nordeste',     '2800308'),
('Palmas',         'PALMAS',          'TO', 'Norte',        '1721000')
ON CONFLICT DO NOTHING;


-- ============================================================
-- Ajusta a sequence/identity depois dos códigos 100 e 101
-- ============================================================
SELECT setval(pg_get_serial_sequence('public.tb_capital', 'cd_capital'),
    (SELECT MAX(cd_capital) FROM public.tb_capital)
);


-- ============================================================
-- TB_ESTACAO_CAPITAL
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_estacao_capital
(cd_estacao    integer GENERATED BY DEFAULT AS IDENTITY,
 cd_capital    integer      NOT NULL,
 wigos         varchar(60)  NOT NULL,
 nome_estacao  varchar(100) NOT NULL,
 status        boolean      NOT NULL DEFAULT true,
 CONSTRAINT pk_tb_estacao_capital PRIMARY KEY (cd_estacao),
 CONSTRAINT fk_tb_estacao_capital FOREIGN KEY (cd_capital) REFERENCES public.tb_capital (cd_capital),
 CONSTRAINT uq_tb_estacao_capital_wigos UNIQUE (wigos)
);


-- ============================================================
-- TB_TEMPERATURA
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_temperatura
(cd_temperatura  integer GENERATED BY DEFAULT AS IDENTITY,
 cd_capital      integer NOT NULL,
 temperatura     numeric(5, 2),
 dt_referencia   timestamp with time zone NOT NULL,
 dt_atualizacao  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 status          boolean NOT NULL DEFAULT true,
CONSTRAINT pk_tb_temperatura PRIMARY KEY (cd_temperatura),
CONSTRAINT fk_tb_temperatura_capital FOREIGN KEY (cd_capital) REFERENCES public.tb_capital (cd_capital),
CONSTRAINT uq_tb_temperatura_capital_referencia UNIQUE (cd_capital, dt_referencia),
CONSTRAINT ck_tb_temperatura_valor CHECK (temperatura IS NULL OR temperatura BETWEEN -90 AND 70)
);

-- ============================================================
-- TB_FERIADO
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tb_feriado
(cd_feriado      integer GENERATED BY DEFAULT AS IDENTITY,
 cd_capital      integer      NOT NULL,
 id_api          uuid         NOT NULL,
 dt_feriado      date         NOT NULL,
 nome            varchar(150) NOT NULL,
 tipo            varchar(20)  NOT NULL,
 uf              char(2),
 codigo_ibge     varchar(10),
 bancario        boolean      NOT NULL DEFAULT false,
 descricao       text,
 dt_atualizacao  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_tb_feriado PRIMARY KEY (cd_feriado),
CONSTRAINT fk_tb_feriado_capital FOREIGN KEY (cd_capital)REFERENCES tb_capital (cd_capital),
CONSTRAINT uq_tb_feriado_capital_api UNIQUE (cd_capital, id_api)
);


-- ============================================================
-- ÍNDICES DE CONSULTA
-- ============================================================
CREATE INDEX IF NOT EXISTS ix_tb_temperatura_capital_data
ON public.tb_temperatura (cd_capital, dt_referencia DESC);

CREATE INDEX IF NOT EXISTS ix_tb_feriado_data
ON public.tb_feriado (dt_feriado);

CREATE INDEX IF NOT EXISTS ix_tb_feriado_capital_data
ON public.tb_feriado (cd_capital, dt_feriado);

CREATE INDEX IF NOT EXISTS ix_tb_moeda_data
ON public.tb_moeda (moeda, dt_referencia DESC);

CREATE INDEX IF NOT EXISTS ix_tb_ipca_data
ON public.tb_ipca (dt_referencia DESC);

CREATE INDEX IF NOT EXISTS ix_tb_selic_data
ON public.tb_selic (dt_referencia DESC);


