[project]
name = "atualizaindicador"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.3",
    "peewee>=4.3.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "schedule>=1.2.2",
]
